# Directories arguments
data_dir: "synthetic_seq"
exp_dir:  "fcn8s_depthnet"
out_dir:  "fcn8s_depthnet"

# Data arguments
img_height:   720
img_width:    1280
num_channels: 1
num_classes:  26

# Train arguments
num_epochs: 200
batch_size: 5
shuffle: True
data_mode: "experiment"
save_every: 5
test_every: 5
max_to_keep: 1

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
pretrained_path: "pretrained_weights/depthnet.npy"

# Misc arguments
verbose: False

