# Directories arguments
exp_dir:  "unet_depthnet_17_noise"
out_dir:  "unet_depthnet_17_noise"
test_data_file: "/jaunt/users/trevor/volcap/SyntheticData/blender/outputs/8_cam_npy/img_test.txt"
test_data_type: ".npy"
train_data_file: "/jaunt/users/trevor/volcap/SyntheticData/blender/outputs/8_cam_npy/img_test.txt"
train_data_type: '.npy'

# Data arguments
# image dimensions are reduced to enable run on my pc
img_height:   200 #740
img_width:    200 #1280
num_channels: 1
num_classes:  17

# Train arguments
num_epochs: 60
batch_size: 8
train_data_len: 44971
shuffle: True
dropout_keep_prob: 0.95
data_mode: "experiment"
save_every: 1
test_every: 5
max_to_keep: 2
weighted_loss: False
random_cropping: False
freeze_encoder: False
clip_width: 1000
depth_range_min: 0
depth_range_max: 255

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
#pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False
