# Directories arguments
data_dir: "synthetic_seq"
exp_dir:  "unet_depthnet"
out_dir:  "unet_depthnet"

# Data arguments
# image dimensions are reduced to enable run on my pc
img_height:   360
img_width:    640
num_channels: 1
num_classes:  28

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "experiment"
save_every: 5
test_every: 1 #5
max_to_keep: 2
weighted_loss: False  #consider this
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
#pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

