# Directories arguments
data_dir: "../../volcap/SyntheticData/blender/outputs/" #"synthetic_seq"
exp_dir:  "unet_depthnet_16_labels_spicy_cam"
out_dir:  "unet_depthnet_16_labels_spicy_cam"
data_file: "/jaunt/users/trevor/volcap/SyntheticData/blender/outputs/spicy_cams"

# Data arguments
# image dimensions are reduced to enable run on my pc
img_height:   200 #740
img_width:    200 #1280
num_channels: 1
num_classes:  16

# Train arguments
num_epochs: 400
batch_size: 8
train_data_len: 2000
shuffle: True
dropout_keep_prob: 0.95
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 2
weighted_loss: False
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
#pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False
